### ISSUE TITLE
Allow uploading whole directories

### ISSUE THREAD

**Issue by ldionne** [melpon/wandbox#153]
It would be awesome if we could upload whole directories and make them available in the include paths of the compiler. My use case is that I'm working on the [Hana](http://github.com/ldionne/hana) C++14 metaprogramming library, and I'd like to have a "Try it online" link where you can try the library on Wandbox. However, in order to do this, I'd need to be able to make my library available on Wandbox so you can type `#include <boost/hana/xxx.hpp>`.

This is related to ldionne/hana#87. As a workaround, we also tried creating a single header containing the whole library and then uploading that on Wandbox. Unfortunately, the header spans several thousand lines and Wandbox does not seem to work with that.

**Comment by kikairoya** [comment]
#154

**Comment by melpon** [comment]
Wandbox allows to make directories.
In order to upload whole directories, you can use Wandbox API. (POST limit size is 1MB)

I tested Boost.Hana library. Script is here: https://gist.github.com/melpon/8c769de03025d4699da6
But, result is...
![UGLY](https://pbs.twimg.com/media/CHOdZPhUkAAOseM.png:large)

http://melpon.org/wandbox/permlink/xnjfZydZ9tMp8V7N

I'm going to fix this UI. I want you to use this UI at the moment.

**Comment by ldionne** [comment]
Thanks a lot for the support! It [works perfectly](http://melpon.org/wandbox/permlink/MZqKhMF7tiaNZdJg). Also, I wrote a somewhat generic [script](https://github.com/ldionne/hana/blob/0cbf6082c2f6ba32ca8678bcad65c9acccce0043/cmake/wandbox.py) to upload a whole library to Wandbox and produce a permalink to it. @krzysztof-jusiak, if you're interested,  take a look at [this](https://github.com/ldionne/hana/commit/0cbf6082c2f6ba32ca8678bcad65c9acccce0043) commit.
